language: python
# before_install:
# - export CHROME_BIN=chromium-browser
# - export DISPLAY=:99.0
# - sh -e /etc/init.d/xvfb start
sudo: false
dist: trusty
python:
 - "3.6"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
 - ./manage.py migrate
 - ./manage.py test ippon

addons:
  postgresql: "9.6"

services:
  - postgresql

notifications:
  slack: ipponforge:POZIxDUMmeddHxK10Ub78v8j
