language: python
sudo: false
dist: trusty
python:
 - "3.7"
os: linux

env:
  global:
    CC_TEST_REPORTER_ID=${CC_REPORTER_ID}

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
 - ./manage.py migrate
 - coverage run ./manage.py test -p *test.py ippon

after_script:
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi


addons:
  postgresql: "9.6"

services:
  - postgresql

notifications:
  slack: ${SLACK_KEY}
