# Generated by Django 2.0.3 on 2018-03-18 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("webpage", models.URLField()),
                ("description", models.TextField()),
                ("city", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.IntegerField(choices=[(0, "Male"), (1, "Female")], max_length=1),
                ),
                (
                    "rank",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "Kyu_6"),
                            (2, "Kyu_5"),
                            (3, "Kyu_4"),
                            (4, "Kyu_3"),
                            (5, "Kyu_2"),
                            (6, "Kyu_1"),
                            (7, "Dan_1"),
                            (8, "Dan_2"),
                            (9, "Dan_3"),
                            (10, "Dan_4"),
                            (11, "Dan_5"),
                            (12, "Dan_6"),
                            (13, "Dan_7"),
                            (14, "Dan_8"),
                        ]
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("birthday", models.DateField()),
                (
                    "club_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="players",
                        to="ippon.Club",
                    ),
                ),
            ],
        ),
    ]
