# Generated by Django 2.0.3 on 2018-04-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ippon", "0004_clubadmin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="club",
            new_name="club_id",
        ),
    ]
