# Generated by Django 2.0.5 on 2018-05-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ippon', '0006_tournament_tournamentadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='finals_depth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
