# Generated by Django 2.0.5 on 2018-06-15 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ippon', '0008_auto_20180602_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField()),
                ('is_registered', models.BooleanField()),
                ('is_qualified', models.BooleanField()),
                ('notes', models.TextField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='ippon.Player')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='ippon.Tournament')),
            ],
        ),
    ]
