# Generated by Django 2.0.5 on 2018-06-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ippon", "0010_auto_20180616_1112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentparticipation",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
