# Generated by Django 2.1.1 on 2018-09-16 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ippon", "0015_auto_20180910_0631"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubadmin",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admins",
                to="ippon.Club",
            ),
        ),
    ]
