# Generated by Django 2.1.1 on 2018-09-20 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ippon", "0016_auto_20180916_0938"),
    ]

    operations = [
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Men"),
                            (1, "Kote"),
                            (2, "Do"),
                            (3, "Tsuki"),
                            (4, "Foul"),
                            (5, "Hansoku"),
                            (6, "Other"),
                        ]
                    ),
                ),
                (
                    "fight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="points",
                        to="ippon.Fight",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="points",
                        to="ippon.Player",
                    ),
                ),
            ],
        ),
    ]
