# Generated by Django 2.1.1 on 2018-09-20 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ippon", "0017_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fight",
            name="team_fight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fights",
                to="ippon.TeamFight",
            ),
        ),
    ]
