# Generated by Django 2.1.1 on 2018-11-01 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ippon', '0020_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroupFight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fight_length', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_phases', to='ippon.Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to='ippon.GroupPhase'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='ippon.Team'),
        ),
        migrations.AddField(
            model_name='groupfight',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_fights', to='ippon.GroupPhase'),
        ),
        migrations.AddField(
            model_name='groupfight',
            name='team_fight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_fight', to='ippon.TeamFight'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='ippon.GroupPhase'),
        ),
    ]
