# Generated by Django 2.1.1 on 2018-11-29 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ippon', '0023_groupphase_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfight',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_fights', to='ippon.Group'),
        ),
    ]
