# Generated by Django 2.1.1 on 2018-12-05 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ippon', '0024_auto_20181129_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_members', to='ippon.Group'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_member', to='ippon.Team'),
        ),
    ]
