# Generated by Django 2.1.4 on 2019-01-02 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ippon", "0025_auto_20181205_1947"),
    ]

    operations = [
        migrations.CreateModel(
            name="CupFight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CupPhase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fight_length", models.IntegerField()),
                ("final_fight_length", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cup_phases",
                        to="ippon.Tournament",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cupfight",
            name="cup_phase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cup_fights",
                to="ippon.CupPhase",
            ),
        ),
        migrations.AddField(
            model_name="cupfight",
            name="previous_aka_fight",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ippon.CupFight",
            ),
        ),
        migrations.AddField(
            model_name="cupfight",
            name="previous_shiro_fight",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ippon.CupFight",
            ),
        ),
        migrations.AddField(
            model_name="cupfight",
            name="team_fight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cup_fight",
                to="ippon.TeamFight",
            ),
        ),
    ]
