# Generated by Django 2.1.4 on 2019-01-02 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ippon", "0026_auto_20190102_1745"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cupfight",
            name="previous_aka_fight",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ippon.CupFight",
            ),
        ),
        migrations.AlterField(
            model_name="cupfight",
            name="previous_shiro_fight",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ippon.CupFight",
            ),
        ),
    ]
