# Generated by Django 2.1.4 on 2019-01-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ippon', '0027_auto_20190102_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupfight',
            name='team_fight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cup_fight', to='ippon.TeamFight'),
        ),
    ]
