# Generated by Django 2.1.4 on 2019-01-02 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ippon', '0030_auto_20190102_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupfight',
            name='previous_aka_fight',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ippon.CupFight'),
        ),
        migrations.AlterField(
            model_name='cupfight',
            name='previous_shiro_fight',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ippon.CupFight'),
        ),
    ]
