# Generated by Django 2.2.1 on 2019-06-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ippon', '0034_auto_20190613_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamfight',
            old_name='result',
            new_name='winner',
        ),
    ]
