# Generated by Django 2.2.1 on 2019-06-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ippon", "0035_auto_20190613_1835"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamfight",
            name="is_started",
            field=models.BooleanField(default=False),
        ),
    ]
