# Generated by Django 2.2.2 on 2019-07-01 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ippon", "0038_auto_20190613_2022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cupfight",
            name="cup_phase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cup_fights",
                to="ippon.CupPhase",
            ),
        ),
        migrations.AlterField(
            model_name="cupphase",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cup_phases",
                to="ippon.Tournament",
            ),
        ),
    ]
