# Generated by Django 3.0.4 on 2020-04-01 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ippon", "0039_auto_20190701_0538"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("icon", models.ImageField(blank=True, null=True, upload_to="")),
                ("banner", models.ImageField(blank=True, null=True, upload_to="")),
                ("start_time", models.DateTimeField()),
                ("registration_start_time", models.DateTimeField()),
                ("registration_end_time", models.DateTimeField()),
                (
                    "event_owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tournament",
            name="event",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ippon.Event"
            ),
        ),
    ]
