# Generated by Django 3.0.5 on 2020-07-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ippon', '0043_auto_20200405_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='locationID',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
